### ISSUE TITLE
Error on installing russound_rio2

### ISSUE THREAD

**Issue by sguex** [nat-neels/homeassistant_russound#1]
Hi, I can't install russound_rio2 as descripted in the readme.
I am always getting the "Platform error media_player.russound_rio2 - Integration 'russound_rio2' not found." if I do "check configuration". All files have been copied to the \config\custom_components\russound_rio2 directory.

# Russound MCA-C5 configuration
media_player:
  - platform: russound_rio2
    host: 192.168.3.10
    name: Russound

I use following versions
core-2021.12.9
Home Assistant OS 7.1
supervisor-2021.12.2

**Comment by ferdaze** [comment]
I have the same issue.

**Comment by nat-neels** [comment]
Updated install instructions.
